// File generated by FlutterFire CLI / Custom configuration
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Configuración predeterminada de Firebase para las plataformas soportadas.
/// Puedes actualizar estos valores con las credenciales exactas de tu consola Firebase:
/// https://console.firebase.google.com/
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions no están configuradas para Linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no están soportadas para esta plataforma.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTradingJournalApp12345',
    appId: '1:123456789012:web:a1b2c3d4e5f67890',
    messagingSenderId: '123456789012',
    projectId: 'trading-journal-firebase-app',
    authDomain: 'trading-journal-firebase-app.firebaseapp.com',
    storageBucket: 'trading-journal-firebase-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTradingJournalApp12345',
    appId: '1:123456789012:android:a1b2c3d4e5f67890',
    messagingSenderId: '123456789012',
    projectId: 'trading-journal-firebase-app',
    storageBucket: 'trading-journal-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTradingJournalApp12345',
    appId: '1:123456789012:ios:a1b2c3d4e5f67890',
    messagingSenderId: '123456789012',
    projectId: 'trading-journal-firebase-app',
    storageBucket: 'trading-journal-firebase-app.appspot.com',
    iosBundleId: 'com.example.tradingJournal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTradingJournalApp12345',
    appId: '1:123456789012:ios:a1b2c3d4e5f67890',
    messagingSenderId: '123456789012',
    projectId: 'trading-journal-firebase-app',
    storageBucket: 'trading-journal-firebase-app.appspot.com',
    iosBundleId: 'com.example.tradingJournal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForTradingJournalApp12345',
    appId: '1:123456789012:web:a1b2c3d4e5f67890',
    messagingSenderId: '123456789012',
    projectId: 'trading-journal-firebase-app',
    authDomain: 'trading-journal-firebase-app.firebaseapp.com',
    storageBucket: 'trading-journal-firebase-app.appspot.com',
  );
}
